services:
  backend:
    build: ./backend
    ports:
      - "8888:8000"
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./data/recipes.db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "9999:80"
    depends_on:
      - backend
    restart: always

volumes:
  backend_data:
